### ISSUE TITLE
Persistir artigos retornados pela Class IEEE_Xplore 

### ISSUE THREAD

**Issue by HugoSoaresFontes** [HugoSoaresFontes/bibliographic-reviewer#1]
Os artigos retornados pela classe IEEE_Xplore, chamada na ImportarDocumentosView, devem ser persistidos no banco de dados. Caso o artigo já exista, ele deve ser atualizado. 

Além disso, o artigo deve ter uma m2m para base de dados.

**Comment by HugoSoaresFontes** [comment]
O mesmo deverá ser feito para as outras classes de consultas que serão criadas.

**Comment by diego-lima** [comment]
@HugoSoaresFontes complemente a [modelagem no diagrama](https://drive.google.com/open?id=1xg9uMKSxrYA49tc1Wm5Iw4Edb5QbXku_)

**Comment by HugoSoaresFontes** [comment]
O modelo revisão se refere a uma revisão bibliográfica. Por exemplo, estamos fazendo a revisão bibliográfica para o doutorado de Sedir. Nessa revisão, vários artigos serão analisados e muitos deles serão fichados. Ficou claro agora?
