### ISSUE TITLE
Criar botão de deletar documento de uma revisão

### ISSUE THREAD

**Issue by diego-lima** [HugoSoaresFontes/bibliographic-reviewer#21]
A deleção de um documento em uma revisão acarretará na deleção do seu fichamento também

Possivelmente a opção de deletar apareceria na interface abaixo:

![screenshot from 2018-03-05 15-27-59](https://user-images.githubusercontent.com/12664294/36992553-0eeeec5e-208a-11e8-9ba6-d4013127449d.png)

**Comment by sedir** [comment]
Funcionalidade implementada no commit b6e2adcf66ddcb9dac5b5e04c2670145c89d66d9
Como ficou na interface:
<img width="803" alt="captura de tela 2018-03-06 as 09 36 58" src="https://user-images.githubusercontent.com/523134/37032661-24269386-2122-11e8-852d-85dbe240ee6f.png">
