### ISSUE TITLE
Erro de permissão (usuário não logado tentando ver página)

### ISSUE THREAD

**Issue by diego-lima** [HugoSoaresFontes/bibliographic-reviewer#27]
Acontece quando não estou logado e acesso a URL mostrada na imagem

![screenshot from 2018-03-10 21-05-05](https://user-images.githubusercontent.com/12664294/37248078-db5aa8d0-24a6-11e8-8511-3f4340c41f38.png)

**Comment by HugoSoaresFontes** [comment]
Corrigido.
